# Partitioning defaults: present ZFS as the default root filesystem.
---
efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 512M
userSwapChoices:
  - none
  - small
  - suspend

drawNestedPartitions: false
alwaysShowPartitionLabels: true
defaultFileSystemType: "zfs"
availableFileSystemTypes: [ "zfs", "ext4", "btrfs", "xfs" ]
enableLuksAutomatedPartitioning: true

initialPartitioningChoice: erase
initialSwapChoice: none
