# Calamares configuration for BETRIEBSSYSTEM.
# Installs the live system onto a target disk with a root-on-ZFS layout.
---
modules-search: [ local, /usr/lib/x86_64-linux-gnu/calamares/modules ]

instances:
- id:     betriebssystem
  module: contextualprocess
  config: contextualprocess.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - zfs
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - luksbootkeyfile
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - bootloader
  - grubcfg
  - initramfscfg
  - initramfs
  - umount
- show:
  - finished

branding: betriebssystem

prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
quit-at-end: false
